### ISSUE TITLE
No automated testing 

### ISSUE THREAD

**Issue by Teg3z** [Teg3z/KoloStesti#50]
Since we are making a good progress on automated building, we should also start implementing automated testing.

**Comment by R4tmax** [comment]
Little harder to do for Python. 

In Java, we used maven builds to validate the project (becuase it fires up the compiler), Python has no compiler tho. (in other words, when you successfully compiled the JAR artifact via Maven, you knew that the code is statically coherent, and you had user testing for runtime errors)

Only reasonable way to go forward is unit and integration testing and other actions taken via dedicated libraries.

I would suggest taking a look at 
A, Logging
B, Unit testing 

For our usecase as a starting step. I am not sure if there are any guarantees to be taken from cx_freeze builds, since pretty much every python error is a runtime one. (read: hard to test statically)
